'use strict';
const root=document.getElementById('app'), key='vilja-democracy-v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>a.map(v=>({v,n:Math.random()})).sort((a,b)=>a.n-b.n).map(x=>x.v);
let saved={weak:[],last:null},session=null,selected=-1,flipped=false;
try{const v=JSON.parse(localStorage.getItem(key));if(v&&Array.isArray(v.weak))saved={weak:v.weak.filter(id=>typeof id==='string'),last:typeof v.last==='string'?v.last:null};}catch(e){}
function save(){try{localStorage.setItem(key,JSON.stringify(saved));}catch(e){document.getElementById('notice').textContent='Resultatet kan inte sparas på den här enheten just nu.';}}
const btn=(text,act,cls='light',extra='')=>`<button class="${cls}" data-action="${act}" ${extra}>${text}</button>`;
function render(html){root.innerHTML=html;window.scrollTo(0,0);}
function home(){session=null;render(`<div class="panel hero"><div class="eyebrow">Inför provet</div><h1>Demokrati</h1><p>Förstå begreppen. Förklara med egna ord.<br>Öva ett område i taget eller testa hela provet.</p><div class="row">${btn('Starta övningsprov','exam','', '')}${btn('Träna svåra ('+saved.weak.length+')','weak','light',saved.weak.length?'':'disabled')}</div><p class="tiny">18 frågor · 6 flervalsfrågor + 12 egna svar · ingen tidspress</p></div>${saved.last?`<p class="tiny muted">Senast: ${esc(saved.last)}</p>`:''}<h2>Sex områden att kunna</h2><div class="grid">${DEMOCRACY.categories.map(c=>`<section class="panel"><div class="icon">${c.icon}</div><h3>${esc(c.title)}</h3><p class="muted">${esc(c.description)}</p>${btn('Öppna område →','category','light',`data-cat="${c.id}"`)}</section>`).join('')}</div><details class="panel space"><summary>Om träningen och underlaget</summary><p class="tiny">Bygger på ”Inför prov – demokrati”. Detta är övningsfrågor, inte lärarens faktiska prov. Träningen kompletterar boken och lektionerna. För årskurs 6 lägger vi extra vikt vid egna förklaringar och exempel.</p><p class="tiny">Fritext bedömer du själv med hjälp av exempelsvar och en checklista. Du behöver inte använda exakt samma ord.</p><p class="tiny">Förtydliganden: EU har 27 medlemsländer. En statsminister godkänns om inte minst 175 ledamöter röstar nej. 4 procent är huvudregeln för riksdagsmandat; det finns även en valkretsregel. Partilistan följer provunderlaget.</p><p class="tiny"><a href="https://www.riksdagen.se/en/how-the-riksdag-works/democracy/forming-a-government/" target="_blank" rel="noopener">Riksdagen: regeringsbildning</a> · <a href="https://european-union.europa.eu/principles-countries-history/eu-countries_sv" target="_blank" rel="noopener">EU:s medlemsländer</a></p><p class="tiny">Resultat och svåra frågor sparas endast i webbläsaren på denna enhet.</p></details>`);}
function category(cat){session=null;const c=DEMOCRACY.categories[cat];render(`<div class="top">${btn('← Områden','home')}<span class="pill">Område ${cat+1} av 6</span></div><section class="panel"><div class="icon">${c.icon}</div><h1>${esc(c.title)}</h1><p class="muted">${esc(c.description)}</p><div class="choices">${btn('1. Begreppskort · lär dig och vänd','cards','',`data-cat="${cat}"`)}${btn('2. Snabbkoll · tre flervalsfrågor','quiz','light',`data-cat="${cat}"`)}${btn('3. Förklara · fem egna svar','written','dark',`data-cat="${cat}"`)}</div><p class="tiny muted">På provet behöver du kunna förklara och ge exempel. Träna gärna högt innan du skriver.</p></section>`);}
function start(mode,cat,items){session={mode,cat,items,index:0,answers:[],revealed:false};question();}
function exam(){const items=DEMOCRACY.categories.flatMap(c=>[...shuffle(DEMOCRACY.quiz.filter(q=>q.cat===c.id)).slice(0,1),...shuffle(DEMOCRACY.cards.filter(q=>q.cat===c.id)).slice(0,2)]);start('exam',null,shuffle(items));}
function current(){return session.items[session.index];}
function top(){return `<div class="top">${btn('← Avsluta','exit')}<span class="tiny muted">${session.index+1} av ${session.items.length}</span></div><div class="bar"><div style="width:${(session.index/session.items.length)*100}%"></div></div>`;}
function question(){selected=-1;session.revealed=false;flipped=false;const q=current(),c=DEMOCRACY.categories[q.cat];
if(session.mode==='cards'){render(`${top()}<p class="eyebrow">${esc(c.title)}</p><button class="flash-card" data-action="flip" aria-label="Vänd begreppskort"><span>${esc(q.term)}</span><small>Förklara själv. Tryck sedan för att vända.</small></button><div class="row space">${btn('← Förra','prev','light',session.index===0?'disabled':'')}${btn('Nästa →','cardNext')}</div><div class="row space">${btn(saved.weak.includes(q.id)?'✓ Markerad som svår':'Markera som svår','mark','light')}</div>`);return;}
render(`${top()}<div class="panel"><p class="eyebrow">${esc(c.title)} · ${q.options?'Välj ett svar':'Förklara själv'}</p><h2 class="question">${esc(q.prompt)}</h2>${q.options?`<div class="choices">${shuffle(q.options.map((text,i)=>({text,i}))).map(o=>btn(esc(o.text),'choose','choice',`data-option="${o.i}" aria-pressed="false"`)).join('')}</div>`:`<label for="answer">Ditt svar</label><textarea id="answer" placeholder="Skriv med egna ord. Ge gärna ett exempel." autocomplete="off"></textarea>`}<div id="feedback" aria-live="polite"></div><div id="actions" class="row space">${btn(session.mode==='exam'?'Spara svar →':q.options?'Kolla svaret':'Visa exempelsvar','submit','',q.options?'disabled':'')}${btn('Vet inte än','skip','light')}</div></div>`);}
function choose(i){if(session.revealed)return;selected=i;root.querySelectorAll('[data-option]').forEach(b=>{const on=Number(b.dataset.option)===i;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});root.querySelector('[data-action="submit"]').disabled=false;}
function mark(id,weak){saved.weak=saved.weak.filter(v=>v!==id);if(weak)saved.weak.push(id);save();}
function record(skip=false){const q=current();if(session.revealed)return;const text=q.options?'':document.getElementById('answer').value.trim();if(!skip&&((q.options&&selected<0)||(!q.options&&!text))){document.getElementById('answer')?.focus();return;}
const r={q,choice:skip?-1:selected,text:skip?'':text,correct:q.options&&!skip?selected===q.correct:false,assessed:!!q.options||skip};session.answers.push(r);session.revealed=true;
if(session.mode==='exam'){next();return;}
if(q.options){mark(q.id,!r.correct);document.getElementById('feedback').innerHTML=`<div class="feedback ${r.correct?'good':'bad'}"><strong>${r.correct?'Rätt!':'Rätt svar: '+esc(q.options[q.correct])}</strong><br>${esc(q.answer)}</div>`;document.getElementById('actions').innerHTML=btn('Nästa →','next','');root.querySelectorAll('[data-option]').forEach(b=>b.disabled=true);}
else{document.getElementById('answer').readOnly=true;document.getElementById('feedback').innerHTML=example(q);document.getElementById('actions').innerHTML=btn('Behöver träna','rateNo','light')+btn('Jag fick med det viktiga','rateYes','');}}
function example(q){return `<div class="feedback"><strong>Exempelsvar</strong><p>${esc(q.answer)}</p><strong>Kontrollera ditt svar:</strong><ul>${q.check.map(k=>`<li>${esc(k)}</li>`).join('')}</ul><span class="tiny">Samma betydelse räcker. Dina ord behöver inte vara identiska.</span></div>`;}
function rate(ok){const r=session.answers[session.answers.length-1];r.correct=ok;r.assessed=true;mark(r.q.id,!ok);next();}
function next(){if(session.index<session.items.length-1){session.index++;question();}else if(session.mode==='exam'){reviewExam();}else results();}
function reviewExam(){const pending=session.answers.findIndex(r=>!r.assessed);if(pending<0){session.answers.forEach(r=>mark(r.q.id,!r.correct));results();return;}session.reviewIndex=pending;const r=session.answers[pending];render(`<div class="top"><span class="pill">Självbedömning</span><span class="tiny">${session.answers.filter(x=>!x.q.options&&x.assessed).length+1} av ${session.answers.filter(x=>!x.q.options).length}</span></div><section class="panel"><h2>${esc(r.q.prompt)}</h2><strong>Ditt svar</strong><blockquote>${esc(r.text||'Inget svar')}</blockquote>${example(r.q)}<div class="row">${btn('Behöver träna','examNo','light')}${btn('Jag fick med det viktiga','examYes','')}</div></section>`);}
function results(){const a=session.answers,mc=a.filter(r=>r.q.options),wr=a.filter(r=>!r.q.options),weak=a.filter(r=>!r.correct);saved.last=`${mc.length?mc.filter(r=>r.correct).length+'/'+mc.length+' flervalsfrågor rätt':''}${mc.length&&wr.length?' · ':''}${wr.length?wr.filter(r=>r.correct).length+'/'+wr.length+' egna svar bedömda som klara':''}`;save();render(`<div class="panel"><p class="eyebrow">Bra jobbat</p><h1>Din träning</h1>${mc.length?`<div class="score">${mc.filter(r=>r.correct).length}/${mc.length}</div><p>Flervalsfrågor rätt</p>`:''}${wr.length?`<h2>${wr.filter(r=>r.correct).length}/${wr.length} egna svar</h2><p class="muted">Som du själv bedömde att du kunde. Detta är ingen automatisk rättning eller ett skolbetyg.</p>`:''}<p>${weak.length?weak.length+' frågor att träna vidare på.':'Du klarade alla frågor i den här omgången!'}</p><div class="row">${btn('Till områdena','home','')}${btn('Träna dessa igen','retry','light',weak.length?'':'disabled')}</div></div><section class="panel"><h2>Alla dina svar</h2>${a.map(r=>`<details class="review"><summary>${r.correct?'✓':'↻'} ${esc(r.q.prompt)}</summary><p><strong>Ditt svar:</strong> ${esc(r.q.options?(r.q.options[r.choice]||'Vet inte än'):(r.text||'Inget svar'))}</p><p><strong>${r.q.options?'Rätt svar':'Exempelsvar'}:</strong> ${esc(r.q.options?r.q.options[r.q.correct]+'. '+r.q.answer:r.q.answer)}</p></details>`).join('')}</section>`);}
root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const cat=Number(b.dataset.cat),action=b.dataset.action;
if(action==='home')home();else if(action==='category')category(cat);else if(action==='exam')exam();else if(action==='cards')start('cards',cat,DEMOCRACY.cards.filter(q=>q.cat===cat));else if(action==='quiz')start('practice',cat,shuffle(DEMOCRACY.quiz.filter(q=>q.cat===cat)));else if(action==='written')start('practice',cat,DEMOCRACY.cards.filter(q=>q.cat===cat));else if(action==='weak'){const items=[...DEMOCRACY.cards,...DEMOCRACY.quiz].filter(q=>saved.weak.includes(q.id));if(items.length)start('practice',null,shuffle(items));}else if(action==='retry')start('practice',null,shuffle(session.answers.filter(r=>!r.correct).map(r=>r.q)));else if(action==='exit'){if(session.mode==='cards'||confirm('Avsluta omgången? Pågående provsvar sparas inte.'))home();}else if(action==='choose')choose(Number(b.dataset.option));else if(action==='submit')record();else if(action==='skip')record(true);else if(action==='next')next();else if(action==='rateYes')rate(true);else if(action==='rateNo')rate(false);else if(action==='examYes'||action==='examNo'){const r=session.answers[session.reviewIndex];r.correct=action==='examYes';r.assessed=true;reviewExam();}else if(action==='flip'){flipped=!flipped;b.classList.toggle('flipped',flipped);b.innerHTML=`<span>${esc(flipped?current().answer:current().term)}</span><small>${flipped?'Tryck för att se begreppet':'Förklara själv. Tryck sedan för att vända.'}</small>`;}else if(action==='prev'){session.index--;question();}else if(action==='cardNext'){if(session.index===session.items.length-1)category(session.cat);else{session.index++;question();}}else if(action==='mark'){mark(current().id,!saved.weak.includes(current().id));b.textContent=saved.weak.includes(current().id)?'✓ Markerad som svår':'Markera som svår';}});
home();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
